---
name: Publish

on:
  push:
    branches:
      - main
  # We allow manually dispatching workflow when needed. Most often, this will not be needed.
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-sdks:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v3
        with:
          # need this custom token to run CI checks on the created PR
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Create Release PR & Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm ci:release
          title: "📦 Publish Package"
          commit: "📦 Publish Package"
        env:
          # need this custom token to run CI checks on the created PR
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

          # probably don't need both of those, but it works!
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
